services:
  app:
    image: ghcr.io/clabs/rockon:${IMAGE_VERSION}
    env_file: .env
    environment:
      STARTMODE: app
    restart: unless-stopped
    volumes:
      - sqlite_data:/app/_db:rw
      - app_socket:/run/rockon
      - static_files:/static_files
      - media_files:/app/uploads
    networks:
      - rockon

  qcluster:
    image: ghcr.io/clabs/rockon:${IMAGE_VERSION}
    env_file: .env
    environment:
      STARTMODE: qcluster
    volumes:
      - sqlite_data:/app/_db:rw
    restart: unless-stopped
    networks:
      - rockon

  proxy:
    image: nginx:alpine
    restart: unless-stopped
    networks:
      - rockon
    ports:
      - "${DOCKER_BIND_INTERFACE}:80:80"
    volumes:
      - app_socket:/run/rockon:ro
      - static_files:/usr/share/nginx/html/static_files:ro
      - media_files:/usr/share/nginx/html/media_files:ro
      - ./contrib/nginx.conf:/etc/nginx/nginx.conf:ro

  redis:
    image: redis:8
    restart: unless-stopped
    volumes:
      - redis_data:/data:rw
    networks:
      - rockon
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  redis_data:
  sqlite_data:
  app_socket:
  static_files:
  media_files:

networks:
  rockon:
