version: "3.8"

services:
  mailhog:
      image: mailhog/mailhog:latest
      restart: unless-stopped
      ports:
        - "${DOCKER_BIND_INTERFACE}:1025:1025"
        - "${DOCKER_BIND_INTERFACE}:8025:8025"

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "${DOCKER_BIND_INTERFACE}:6379:6379"
    volumes:
      - redis-data:/data:rw
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 3s
      retries: 5

  bb-legacy_proxy:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./contrib/bblegacy-nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  postgres-data:
  redis-data:
