version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: ${POSTGRES_INITDB_ARGS}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PGTZ: ${POSTGRES_PGTZ}
      POSTGRES_TZ: ${POSTGRES_TZ}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
    ports:
      - "${DOCKER_BIND_INTERFACE}:5432:5432"

  app:
    image: ghcr.io/clabs/rockon:${IMAGE_VERSION}
    # build:
    #  dockerfile: docker/Dockerfile
    #  context: .
    env_file: .env
    environment:
      STARTMODE: app
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "${DOCKER_BIND_INTERFACE}:8000:8000"


volumes:
  postgres-data:
    driver: local
