# Generated by Django 4.1.5 on 2023-01-23 10:39

from __future__ import annotations

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magiclink",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="magic_links",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
