# Generated by Django 4.2 on 2023-04-20 15:45

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0002_alter_organisation_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="internal_comment",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="org_address",
            field=models.CharField(blank=True, default=None, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="org_address_extension",
            field=models.CharField(blank=True, default=None, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="org_house_number",
            field=models.CharField(blank=True, default=None, max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="org_place",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="org_zip",
            field=models.CharField(blank=True, default=None, max_length=31, null=True),
        ),
    ]
