# Generated by Django 4.2.4 on 2023-08-29 16:32

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0006_userprofile_contact_mail"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="new_email",
            field=models.EmailField(default=None, max_length=1024, null=True),
        ),
    ]
