# Generated by Django 4.2.6 on 2023-11-03 16:40

from __future__ import annotations

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("crm", "0008_accountcontext_userprofile_account_context"),
        ("crm", "0009_alter_accountcontext_description_and_more"),
        ("crm", "0010_alter_userprofile_account_context"),
        ("crm", "0011_alter_userprofile_account_context"),
        ("crm", "0012_userprofile_birthday"),
        ("crm", "0013_alter_userprofile_events"),
        ("crm", "0014_remove_userprofile_contact_mail"),
    ]

    dependencies = [
        ("crm", "0007_emailverification_new_email"),
        ("event", "0005_alter_event_sub_event_of"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountContext",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=1024)),
                ("name", models.CharField(blank=True, max_length=1024, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="account_context",
            field=models.ManyToManyField(
                blank=True, default=None, to="crm.accountcontext"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="birthday",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="events",
            field=models.ManyToManyField(blank=True, default=None, to="event.event"),
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="contact_mail",
        ),
    ]
