# Generated by Django 4.2.7 on 2023-11-04 11:54

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0008_refactor_1"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={"ordering": ["created_at"]},
        ),
    ]
