# Generated by Django 4.1.7 on 2023-03-19 13:38

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exhibitors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exhibitor",
            name="state",
            field=models.CharField(
                choices=[
                    ("unknown", "Unbekannt"),
                    ("contacted", "Kontakt aufgenommen"),
                    ("confirmed", "Bestätigt"),
                    ("rejected", "Abgelehnt"),
                ],
                default="unknown",
                max_length=12,
            ),
        ),
    ]
