# Generated by Django 4.1.6 on 2023-02-18 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0001_initial"),
        ("exhibitors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exhibitor_attendances",
                to="event.event",
            ),
        ),
    ]
