# Generated by Django 4.2 on 2023-04-20 15:34

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exhibitors", "0002_alter_exhibitor_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exhibitor",
            name="general_note",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="exhibitor",
            name="internal_comment",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="exhibitor",
            name="market_id",
            field=models.CharField(
                blank=True, default=None, max_length=255, null=True, unique=True
            ),
        ),
    ]
