# Generated by Django 4.2.7 on 2023-11-04 11:52

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exhibitors", "0003_alter_exhibitor_general_note_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exhibitor",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="exhibitorattendance",
            options={"ordering": ["created_at"]},
        ),
    ]
