# Generated by Django 4.1.6 on 2023-02-20 18:29

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crew", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crewmember",
            name="is_underaged",
        ),
        migrations.AddField(
            model_name="crewmember",
            name="is_adult",
            field=models.BooleanField(default=False),
        ),
    ]
