# Generated by Django 4.1.7 on 2023-03-19 11:56

from __future__ import annotations

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crew", "0002_teamcategory_crewmember_intressted_in_team_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crewmember",
            name="nutrition",
            field=models.CharField(
                choices=[
                    ("unknown", "Unbekannt"),
                    ("vegan", "Vegan"),
                    ("vegetarian", "Vegetarisch"),
                    ("omnivore", "Omnivor"),
                ],
                default="unknown",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="AttendanceAddition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("amount", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crew.attendance",
                    ),
                ),
            ],
        ),
    ]
