# Generated by Django 4.1.7 on 2023-03-19 14:06

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crew", "0003_alter_crewmember_nutrition_attendanceaddition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crewmember",
            name="attendance",
            field=models.ManyToManyField(
                blank=True, related_name="crew_members", to="crew.attendance"
            ),
        ),
    ]
