# Generated by Django 4.2.1 on 2023-05-19 10:39

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crew", "0004_alter_crewmember_attendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shirt",
            name="size",
            field=models.CharField(
                choices=[
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("2XL", "2XL"),
                    ("3XL", "3XL"),
                    ("4XL", "4XL"),
                ],
                max_length=12,
            ),
        ),
    ]
