# Generated by Django 4.2.1 on 2023-06-26 12:35

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crew", "0005_alter_shirt_size"),
    ]

    operations = [
        migrations.RenameField(
            model_name="crewmember",
            old_name="intressted_in",
            new_name="interested_in",
        ),
    ]
