# Generated by Django 6.0.8 on 2026-08-16 10:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('rockonbase', '0016_passkeycredential_device_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('body_markdown', models.TextField()),
                ('body_html', models.TextField(blank=True, editable=False)),
                (
                    'status',
                    models.CharField(
                        choices=[('draft', 'Entwurf'), ('published', 'Veröffentlicht')],
                        default='draft',
                        max_length=16,
                    ),
                ),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('audience_crew', models.BooleanField(default=False)),
                ('audience_bands', models.BooleanField(default=False)),
                ('audience_exhibitors', models.BooleanField(default=False)),
                (
                    'author',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='news_posts',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'event',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='news_posts',
                        to='rockonbase.event',
                    ),
                ),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
