# Generated by Django 6.0.8 on 2026-08-16 10:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rockonnews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='newspost',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('audience_crew', True),
                    ('audience_bands', True),
                    ('audience_exhibitors', True),
                    _connector='OR',
                ),
                name='newspost_audience_explicit',
            ),
        ),
    ]
