# Generated by Django 6.0.2 on 2026-02-18 12:20

import rockon.exhibitors.models.exhibitor
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rockonexhibitors', '0002_exhibitor_about_note_exhibitor_offer_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='logo',
            field=models.ImageField(
                blank=True,
                default=None,
                help_text='Logo oder Bild des Ausstellers',
                null=True,
                upload_to=rockon.exhibitors.models.exhibitor.exhibitor_logo_path,
            ),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='website',
            field=models.URLField(
                blank=True,
                default=None,
                help_text='Internetadresse der Organisation oder des Angebots',
                max_length=500,
                null=True,
            ),
        ),
    ]
