# Generated by Django 6.0.2 on 2026-02-18 12:41

import rockon.exhibitors.models.exhibitor
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rockonexhibitors', '0003_exhibitor_logo_exhibitor_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitor',
            name='logo',
            field=models.FileField(
                blank=True,
                default=None,
                help_text='Logo oder Bild des Ausstellers (JPG, PNG, EPS oder PDF)',
                null=True,
                upload_to=rockon.exhibitors.models.exhibitor.exhibitor_logo_path,
            ),
        ),
    ]
