# Generated by Django 4.2 on 2023-04-14 16:17

from __future__ import annotations

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0005_alter_event_sub_event_of"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bands", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bandmember",
            name="event",
        ),
        migrations.RemoveField(
            model_name="timeslot",
            name="band",
        ),
        migrations.AddField(
            model_name="band",
            name="slot",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="band",
                to="bands.timeslot",
            ),
        ),
        migrations.AddField(
            model_name="bandmember",
            name="nutrition",
            field=models.CharField(
                choices=[
                    ("unknown", "Unbekannt"),
                    ("vegan", "Vegan"),
                    ("vegetarian", "Vegetarisch"),
                    ("omnivore", "Omnivor"),
                ],
                default="unknown",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="bandmember",
            name="position",
            field=models.CharField(
                choices=[
                    ("unknown", "Unbekannt"),
                    ("merch", "Merchandise"),
                    ("band", "Band"),
                    ("hand", "Stagehand"),
                ],
                default="unknown",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="band",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="band",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="band",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bands",
                to="event.event",
            ),
        ),
        migrations.AlterField(
            model_name="bandmember",
            name="band",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="band_members",
                to="bands.band",
            ),
        ),
        migrations.AlterField(
            model_name="bandmember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeslots",
                to="bands.stage",
            ),
        ),
    ]
