# Generated by Django 4.2.7 on 2023-11-05 21:16

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bands", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="band",
            name="are_students",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="band",
            name="cover_letter",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="band",
            name="facebook",
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="band",
            name="federal_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BW", "Baden-Württemberg"),
                    ("BY", "Bayern"),
                    ("BE", "Berlin"),
                    ("BB", "Brandenburg"),
                    ("HB", "Bremen"),
                    ("HH", "Hamburg"),
                    ("HE", "Hessen"),
                    ("MV", "Mecklenburg-Vorpommern"),
                    ("NI", "Niedersachsen"),
                    ("NW", "Nordrhein-Westfalen"),
                    ("RP", "Rheinland-Pfalz"),
                    ("SL", "Saarland"),
                    ("SN", "Sachsen"),
                    ("ST", "Sachsen-Anhalt"),
                    ("SH", "Schleswig-Holstein"),
                    ("TH", "Thüringen"),
                    ("XX", "Nicht in Deutschland"),
                ],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="band",
            name="genre",
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="band",
            name="has_management",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="band",
            name="homepage",
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
