# Generated by Django 4.2 on 2023-04-14 19:52

from __future__ import annotations

import django.db.models.deletion
import django.utils.crypto
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crew", "0004_alter_crewmember_attendance"),
        ("bands", "0002_remove_bandmember_event_remove_timeslot_band_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="band",
            name="slot",
        ),
        migrations.AddField(
            model_name="band",
            name="slug",
            field=models.SlugField(default=None, blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="timeslot",
            name="band",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slot",
                to="bands.band",
            ),
        ),
        migrations.AddField(
            model_name="timeslot",
            name="day",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeslots",
                to="crew.attendance",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="end",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="start",
            field=models.TimeField(),
        ),
    ]
