# Generated by Django 4.2 on 2023-04-30 13:04

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bands", "0003_remove_band_slot_band_slug_timeslot_band_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bandmember",
            name="position",
            field=models.CharField(
                choices=[
                    ("unknown", "Unbekannt"),
                    ("merch", "Merchandise"),
                    ("band", "Band"),
                    ("hand", "Stagehand"),
                    ("technican", "Techniker"),
                    ("support", "Support"),
                ],
                default="unknown",
                max_length=12,
            ),
        ),
    ]
