# Generated by Django 4.2.7 on 2023-11-10 15:30

from __future__ import annotations

from django.db import migrations, models

import bands.models.band_media


class Migration(migrations.Migration):
    dependencies = [
        ("bands", "0004_bandmedia"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bandmedia",
            options={"ordering": ["band", "media_type", "created_at"]},
        ),
        migrations.AlterField(
            model_name="bandmedia",
            name="file",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to=bands.models.band_media.band_media_path,
            ),
        ),
    ]
