# Generated by Django 4.2.1 on 2023-05-19 15:29

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bands", "0004_alter_bandmember_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="band",
            name="techrider",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
