# Generated by Django 4.2.7 on 2023-11-04 11:52

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bands", "0005_band_techrider"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="band",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="bandmember",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="stage",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="timeslot",
            options={"ordering": ["created_at"]},
        ),
    ]
