# Generated by Django 4.1.7 on 2023-03-05 20:02

from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="signup_is_open",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="event",
            name="signup_type",
            field=models.CharField(
                choices=[
                    ("unknown", "Unbekannt"),
                    ("crew", "Crew"),
                    ("exhibitor", "Austeller"),
                ],
                default="unknown",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="sub_event_of",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_events",
                to="event.event",
            ),
        ),
    ]
