# Generated by Django 4.2.7 on 2023-11-04 11:52

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0005_alter_event_sub_event_of"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="timeline",
            options={"ordering": ["created_at"]},
        ),
    ]
