# Generated by Django 4.2.7 on 2023-11-11 12:45

from __future__ import annotations

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rockonbase", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountContext",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="account_context",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="account_context",
            field=models.ManyToManyField(
                blank=True, default=None, to="rockonbase.accountcontext"
            ),
        ),
    ]
