# Generated by Django 4.2.7 on 2023-12-02 15:28

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rockonbase", "0004_remove_userprofile_account_context"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AccountContext",
        ),
        migrations.AlterField(
            model_name="event",
            name="signup_is_open",
            field=models.BooleanField(
                default=True,
                help_text="Crew Anmeldung und Bandbewerbung werden auf der Website angezeigt",
            ),
        ),
    ]
