# Generated by Django 5.0.6 on 2024-05-25 13:20

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rockonbase", "0006_event_bid_vote_allowed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="signup_type",
            field=models.CharField(
                choices=[
                    ("unknown", "Unbekannt"),
                    ("crew", "Crew"),
                    ("exhibitor", "Aussteller"),
                ],
                default="unknown",
                max_length=12,
            ),
        ),
    ]
