# Generated by Django 5.1.2 on 2024-10-25 18:35

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rockonbase', '0007_alter_event_signup_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='new_email',
            field=models.EmailField(
                blank=True, default=None, max_length=1024, null=True
            ),
        ),
    ]
