# Generated by Django 5.1.4 on 2025-01-07 09:02

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rockonbase", "0008_alter_emailverification_new_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="bid_browsing_allowed",
            field=models.BooleanField(
                default=False, help_text="Bandbewerbungen einsehbar"
            ),
        ),
    ]
