# Generated by Django 6.0.2 on 2026-02-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rockonbase', '0009_event_bid_browsing_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bid_browsing_allowed',
            field=models.BooleanField(
                db_default=False, default=False, help_text='Bandbewerbungen einsehbar'
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='bid_vote_allowed',
            field=models.BooleanField(
                db_default=False, default=False, help_text='Bandbewertung aktiv'
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_current',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='show_on_landing_page',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='signup_is_open',
            field=models.BooleanField(
                db_default=True,
                default=True,
                help_text='Crew Anmeldung und Bandbewerbung werden auf der Website angezeigt',
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='signup_type',
            field=models.CharField(
                choices=[
                    ('unknown', 'Unbekannt'),
                    ('crew', 'Crew'),
                    ('exhibitor', 'Aussteller'),
                ],
                db_default='unknown',
                default='unknown',
                max_length=12,
            ),
        ),
    ]
