# Generated by Django 6.0.2 on 2026-03-15

from __future__ import annotations

from collections import defaultdict
from typing import Dict, List, Optional

from django.conf import settings
from django.db import migrations, transaction

PROFILE_VALUE_FIELDS = [
    'nick_name',
    'phone',
    'address',
    'address_extension',
    'address_housenumber',
    'zip_code',
    'place',
    'comment',
    'birthday',
    'internal_comment',
]


def normalize_email(value: Optional[str]) -> str:
    if value is None:
        return ''
    return value.strip().lower()


def has_value(value) -> bool:
    return value is not None and value != ''


def merge_duplicate_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Band = apps.get_model('rockonbands', 'Band')
    BandMember = apps.get_model('rockonbands', 'BandMember')
    BandReaction = apps.get_model('rockonbands', 'BandReaction')
    BandVote = apps.get_model('rockonbands', 'BandVote')
    Comment = apps.get_model('rockonbands', 'Comment')
    CrewMember = apps.get_model('rockoncrew', 'CrewMember')
    Team = apps.get_model('rockoncrew', 'Team')
    EmailVerification = apps.get_model('rockonbase', 'EmailVerification')
    MagicLink = apps.get_model('rockonbase', 'MagicLink')
    Organisation = apps.get_model('rockonbase', 'Organisation')
    UserProfile = apps.get_model('rockonbase', 'UserProfile')

    grouped_user_ids: Dict[str, List[int]] = defaultdict(list)
    users = (
        User.objects.exclude(email__isnull=True).exclude(email='').only('id', 'email')
    )
    for user in users.iterator():
        normalized_email = normalize_email(user.email)
        if normalized_email:
            grouped_user_ids[normalized_email].append(user.id)

    duplicate_groups = [
        (email, sorted(user_ids))
        for email, user_ids in grouped_user_ids.items()
        if len(user_ids) > 1
    ]
    duplicate_groups.sort(key=lambda item: item[0])

    for normalized_email, user_ids in duplicate_groups:
        canonical = User.objects.get(pk=user_ids[0])
        duplicate_users = list(User.objects.filter(pk__in=user_ids[1:]).order_by('id'))

        profiles = list(
            UserProfile.objects.filter(user_id__in=user_ids).order_by(
                '-updated_at', '-created_at'
            )
        )

        canonical_profile = UserProfile.objects.filter(user=canonical).first()
        if canonical_profile is None:
            canonical_profile = UserProfile.objects.create(user=canonical)

        # Most recently updated non-empty profile value wins.
        for field_name in PROFILE_VALUE_FIELDS:
            value_set = False
            for profile in profiles:
                value = getattr(profile, field_name)
                if has_value(value):
                    setattr(canonical_profile, field_name, value)
                    value_set = True
                    break
            if not value_set and hasattr(canonical_profile, field_name):
                setattr(
                    canonical_profile,
                    field_name,
                    getattr(canonical_profile, field_name),
                )

        # Verification state follows the most recently updated profile.
        if profiles:
            canonical_profile.email_is_verified = profiles[0].email_is_verified

        canonical_profile.save()

        for profile in profiles:
            event_ids = list(profile.events.values_list('pk', flat=True))
            if event_ids:
                canonical_profile.events.add(*event_ids)

        for duplicate in duplicate_users:
            Band.objects.filter(contact=duplicate).update(contact=canonical)
            BandMember.objects.filter(user=duplicate).update(user=canonical)
            Comment.objects.filter(user=duplicate).update(user=canonical)
            CrewMember.objects.filter(user=duplicate).update(user=canonical)
            MagicLink.objects.filter(user=duplicate).update(user=canonical)

            for field_name in ('lead', 'vize_lead'):
                canonical_assignment = Team.objects.filter(
                    **{field_name: canonical}
                ).first()
                duplicate_assignments = Team.objects.filter(
                    **{field_name: duplicate}
                ).order_by('created_at', 'id')
                for assignment in duplicate_assignments:
                    if canonical_assignment is None:
                        setattr(assignment, field_name, canonical)
                        assignment.save(update_fields=[field_name])
                        canonical_assignment = assignment
                    else:
                        setattr(assignment, field_name, None)
                        assignment.save(update_fields=[field_name])

            duplicate_verification = EmailVerification.objects.filter(
                user=duplicate
            ).first()
            canonical_verification = EmailVerification.objects.filter(
                user=canonical
            ).first()
            if duplicate_verification:
                if canonical_verification:
                    duplicate_verification.delete()
                else:
                    duplicate_verification.user = canonical
                    duplicate_verification.save(update_fields=['user'])

            duplicate_votes = BandVote.objects.filter(user=duplicate).order_by(
                'created_at', 'id'
            )
            for duplicate_vote in duplicate_votes:
                canonical_vote = (
                    BandVote.objects.filter(user=canonical, band=duplicate_vote.band)
                    .exclude(pk=duplicate_vote.pk)
                    .order_by('-created_at', '-id')
                    .first()
                )
                if canonical_vote is None:
                    duplicate_vote.user = canonical
                    duplicate_vote.save(update_fields=['user'])
                    continue

                duplicate_is_newer = (
                    duplicate_vote.created_at > canonical_vote.created_at
                )
                if duplicate_is_newer:
                    canonical_vote.delete()
                    duplicate_vote.user = canonical
                    duplicate_vote.save(update_fields=['user'])
                else:
                    duplicate_vote.delete()

            duplicate_reactions = BandReaction.objects.filter(user=duplicate).order_by(
                'created_at', 'id'
            )
            for duplicate_reaction in duplicate_reactions:
                canonical_reaction = (
                    BandReaction.objects.filter(
                        user=canonical,
                        band=duplicate_reaction.band,
                        emoji=duplicate_reaction.emoji,
                    )
                    .exclude(pk=duplicate_reaction.pk)
                    .order_by('-created_at', '-id')
                    .first()
                )
                if canonical_reaction is None:
                    duplicate_reaction.user = canonical
                    duplicate_reaction.save(update_fields=['user'])
                    continue

                duplicate_is_newer = (
                    duplicate_reaction.created_at > canonical_reaction.created_at
                )
                if duplicate_is_newer:
                    canonical_reaction.delete()
                    duplicate_reaction.user = canonical
                    duplicate_reaction.save(update_fields=['user'])
                else:
                    duplicate_reaction.delete()

            organisations = Organisation.objects.filter(members=duplicate)
            for organisation in organisations:
                organisation.members.add(canonical)
                organisation.members.remove(duplicate)

            duplicate.email = f'merged+{duplicate.id}@invalid.local'
            duplicate.username = f'merged_user_{duplicate.id}'
            duplicate.is_active = False
            # Historical migration models do not expose helper methods.
            # '!' marks an unusable password in Django auth.
            duplicate.password = '!'
            duplicate.save(update_fields=['email', 'username', 'is_active', 'password'])

        canonical.email = normalized_email
        if (
            not User.objects.exclude(pk=canonical.pk)
            .filter(username=normalized_email)
            .exists()
        ):
            canonical.username = normalized_email
        canonical.save(update_fields=['email', 'username'])


@transaction.atomic
def forward(apps, schema_editor):
    merge_duplicate_users(apps, schema_editor)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rockonbands', '0026_alter_band_bid_status'),
        (
            'rockoncrew',
            '0005_alter_crewmember_nutrition_alter_crewmember_state_and_more',
        ),
        ('rockonbase', '0010_alter_event_bid_browsing_allowed_and_more'),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop),
    ]
