# Generated by Django 6.0.2 on 2026-03-15

from __future__ import annotations

from django.db import migrations
from django.db.models import Count
from django.db.models.functions import Lower, Trim


def assert_no_normalized_email_duplicates(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    duplicates_exist = (
        User.objects.exclude(email__isnull=True)
        .annotate(normalized_email=Lower(Trim('email')))
        .exclude(normalized_email='')
        .values('normalized_email')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
        .exists()
    )

    if duplicates_exist:
        raise RuntimeError(
            'Cannot create unique normalized email index because duplicates still exist.'
        )


class Migration(migrations.Migration):
    dependencies = [
        ('rockonbase', '0011_normalize_and_merge_duplicate_emails'),
    ]

    operations = [
        migrations.RunPython(
            assert_no_normalized_email_duplicates, migrations.RunPython.noop
        ),
        migrations.RunSQL(
            sql=(
                'CREATE UNIQUE INDEX IF NOT EXISTS auth_user_email_normalized_uniq '
                'ON auth_user (LOWER(TRIM(email))) '
                "WHERE email IS NOT NULL AND TRIM(email) <> '';"
            ),
            reverse_sql='DROP INDEX IF EXISTS auth_user_email_normalized_uniq;',
        ),
    ]
