# Generated by Django 6.0.2 on 2026-03-15

from __future__ import annotations

from django.db import migrations


def normalize_all_user_emails(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    users = (
        User.objects.exclude(email__isnull=True).exclude(email='').only('id', 'email')
    )

    for user in users.iterator():
        normalized_email = user.email.strip().lower()
        if user.email != normalized_email:
            user.email = normalized_email
            user.save(update_fields=['email'])


class Migration(migrations.Migration):
    dependencies = [
        ('rockonbase', '0012_add_unique_index_for_normalized_user_email'),
    ]

    operations = [
        migrations.RunPython(normalize_all_user_emails, migrations.RunPython.noop),
    ]
