# Generated by Django 6.0.2 on 2026-03-15

from __future__ import annotations

from django.db import migrations
from django.db.models import Count
from django.db.models.functions import Lower, Trim


def normalize_all_usernames(apps, schema_editor):
    User = apps.get_model('auth', 'User')

    duplicates_exist = (
        User.objects.exclude(username__isnull=True)
        .exclude(username='')
        .annotate(normalized_username=Lower(Trim('username')))
        .exclude(normalized_username='')
        .values('normalized_username')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
        .exists()
    )

    if duplicates_exist:
        raise RuntimeError(
            'Cannot lowercase usernames because normalized username duplicates exist.'
        )

    users = (
        User.objects.exclude(username__isnull=True)
        .exclude(username='')
        .only('id', 'username')
    )
    for user in users.iterator():
        normalized_username = user.username.strip().lower()
        if user.username != normalized_username:
            user.username = normalized_username
            user.save(update_fields=['username'])


class Migration(migrations.Migration):
    dependencies = [
        ('rockonbase', '0013_normalize_all_user_emails_to_lowercase'),
    ]

    operations = [
        migrations.RunPython(normalize_all_usernames, migrations.RunPython.noop),
    ]
