# Generated by Django 6.0.5 on 2026-05-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockonbase', '0015_passkeycredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='passkeycredential',
            name='device_info',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
