# Generated by Django 6.0.8 on 2026-08-16 08:16
#
# Squashes rockonbands 0001_initial through 0027_alter_bandmember_position.
# The three RunPython functions below are copied verbatim from the
# migrations they originated in (0008, 0016, 0022) — Django's squash
# optimizer can't safely auto-copy function code across files.
#
# The 27 original migration files are intentionally kept alongside this
# one for now. Any database that already applied them needs to run
# `migrate` at least once while both this squash and the originals are
# present — only then does Django record this squashed migration itself
# as applied, satisfying `base.0011`'s dependency on
# `rockonbands.0026_alter_band_bid_status`. Only after that has happened
# everywhere is it safe to delete the 27 originals and drop `replaces`
# below (see Django's migration-squashing docs).

from __future__ import annotations

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import rockon.bands.models.band_media
import rockon.library.guid


def set_bid_complete(apps, schema_editor):
    Band = apps.get_model('rockonbands', 'Band')
    for band in Band.objects.all():
        band.save()


def copy_urls_to_bandmedia(apps, schema_editor):
    Band = apps.get_model('rockonbands', 'Band')
    BandMedia = apps.get_model('rockonbands', 'BandMedia')
    for band in Band.objects.all():
        if band.facebook:
            BandMedia.objects.create(
                band=band,
                media_type='web',
                url=band.facebook,
            )
        if band.homepage:
            BandMedia.objects.create(
                band=band,
                media_type='web',
                url=band.homepage,
            )


def fix_corrupted_bid_status(apps, schema_editor):
    Band = apps.get_model('rockonbands', 'Band')
    Band.objects.filter(bid_status='lineupLine Up').update(bid_status='lineup')


class Migration(migrations.Migration):
    replaces = [
        ('rockonbands', '0001_initial'),
        ('rockonbands', '0002_alter_band_name'),
        ('rockonbands', '0003_band_repeated_track_band_track'),
        ('rockonbands', '0004_alter_band_genre'),
        ('rockonbands', '0005_bandvote'),
        ('rockonbands', '0006_bandmedia_encoded_file'),
        ('rockonbands', '0007_alter_bandmedia_encoded_file'),
        ('rockonbands', '0008_band_bid_complete'),
        ('rockonbands', '0009_alter_band_track'),
        ('rockonbands', '0010_alter_bandmember_nutrition'),
        ('rockonbands', '0011_alter_band_options'),
        ('rockonbands', '0012_bandvote_event'),
        ('rockonbands', '0013_band_mean_age_under_27'),
        ('rockonbands', '0014_band_is_coverband'),
        ('rockonbands', '0015_alter_bandmedia_media_type'),
        ('rockonbands', '0016_remove_band_facebook_remove_band_homepage'),
        ('rockonbands', '0017_alter_band_contact'),
        ('rockonbands', '0018_alter_bandmedia_file'),
        ('rockonbands', '0019_comment'),
        ('rockonbands', '0020_alter_band_bid_status'),
        ('rockonbands', '0021_alter_band_bid_status'),
        ('rockonbands', '0022_fix_corrupted_bid_status'),
        (
            'rockonbands',
            '0023_alter_band_are_students_alter_band_bid_complete_and_more',
        ),
        ('rockonbands', '0024_bandvote_unique_band_user'),
        ('rockonbands', '0025_bandreaction'),
        ('rockonbands', '0026_alter_band_bid_status'),
        ('rockonbands', '0027_alter_bandmember_position'),
    ]

    dependencies = [
        ('rockonbase', '0001_initial'),
        ('rockonbase', '0005_delete_accountcontext_alter_event_signup_is_open'),
        ('rockonbase', '0006_event_bid_vote_allowed'),
        ('rockoncrew', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'guid',
                    models.CharField(
                        default=rockon.library.guid.guid, max_length=255, unique=True
                    ),
                ),
                (
                    'slug',
                    models.SlugField(blank=True, default=None, null=True, unique=True),
                ),
                (
                    'name',
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                ('has_management', models.BooleanField(default=False)),
                ('are_students', models.BooleanField(default=False)),
                (
                    'genre',
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
                (
                    'federal_state',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('BW', 'Baden-Württemberg'),
                            ('BY', 'Bayern'),
                            ('BE', 'Berlin'),
                            ('BB', 'Brandenburg'),
                            ('HB', 'Bremen'),
                            ('HH', 'Hamburg'),
                            ('HE', 'Hessen'),
                            ('MV', 'Mecklenburg-Vorpommern'),
                            ('NI', 'Niedersachsen'),
                            ('NW', 'Nordrhein-Westfalen'),
                            ('RP', 'Rheinland-Pfalz'),
                            ('SL', 'Saarland'),
                            ('SN', 'Sachsen'),
                            ('ST', 'Sachsen-Anhalt'),
                            ('SH', 'Schleswig-Holstein'),
                            ('TH', 'Thüringen'),
                            ('XX', 'Nicht in Deutschland'),
                        ],
                        default=None,
                        max_length=255,
                        null=True,
                    ),
                ),
                ('homepage', models.URLField(blank=True, default=None, null=True)),
                ('facebook', models.URLField(blank=True, default=None, null=True)),
                ('cover_letter', models.TextField(blank=True, default=None, null=True)),
                (
                    'bid_status',
                    models.CharField(
                        choices=[
                            ('unknown', 'Unbekannt'),
                            ('pending', 'Bearbeitung'),
                            ('accepted', 'Angenommen'),
                            ('declined', 'Abgelehnt'),
                        ],
                        default='unknown',
                        max_length=32,
                    ),
                ),
                ('techrider', models.JSONField(blank=True, default=dict, null=True)),
                (
                    'contact',
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='band',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'event',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='bands',
                        to='rockonbase.event',
                    ),
                ),
                ('repeated', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                (
                    'event',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='rockonbase.event',
                    ),
                ),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                (
                    'band',
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='slot',
                        to='rockonbands.band',
                    ),
                ),
                (
                    'day',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='timeslots',
                        to='rockoncrew.attendance',
                    ),
                ),
                (
                    'stage',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='timeslots',
                        to='rockonbands.stage',
                    ),
                ),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BandMember',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'nutrition',
                    models.CharField(
                        choices=[
                            ('unknown', 'Unbekannt'),
                            ('vegan', 'Vegan'),
                            ('vegetarian', 'Vegetarisch'),
                            ('omnivore', 'Omnivor'),
                        ],
                        default='unknown',
                        max_length=12,
                    ),
                ),
                (
                    'position',
                    models.CharField(
                        choices=[
                            ('unknown', 'Unbekannt'),
                            ('merch', 'Merchandise'),
                            ('band', 'Band'),
                            ('hand', 'Stagehand'),
                            ('technican', 'Techniker'),
                            ('support', 'Support'),
                        ],
                        default='unknown',
                        max_length=12,
                    ),
                ),
                (
                    'band',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='band_members',
                        to='rockonbands.band',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                (
                    'slug',
                    models.SlugField(blank=True, default=None, null=True, unique=True),
                ),
                ('active', models.BooleanField(default=True)),
                (
                    'events',
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        related_name='tracks',
                        to='rockonbase.event',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='band',
            name='track',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='bands',
                to='rockonbands.track',
            ),
        ),
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='BandVote',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vote', models.IntegerField()),
                (
                    'band',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='votes',
                        to='rockonbands.band',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='band_votes',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['band', 'user', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BandMedia',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'media_type',
                    models.CharField(
                        choices=[
                            ('unknown', 'Unbekannt'),
                            ('document', 'Dokument'),
                            ('audio', 'Audio'),
                            ('link', 'Link'),
                            ('press_photo', 'Pressefoto'),
                            ('logo', 'Logo'),
                        ],
                        default='unknown',
                        max_length=32,
                    ),
                ),
                ('url', models.URLField(blank=True, default=None, null=True)),
                (
                    'file',
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to=rockon.bands.models.band_media.band_media_path,
                    ),
                ),
                (
                    'thumbnail',
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to=''
                    ),
                ),
                (
                    'file_name_original',
                    models.CharField(
                        blank=True, default=None, max_length=512, null=True
                    ),
                ),
                (
                    'band',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='media',
                        to='rockonbands.band',
                    ),
                ),
                (
                    'encoded_file',
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to=rockon.bands.models.band_media.band_media_path,
                    ),
                ),
            ],
            options={
                'ordering': ['band', 'media_type', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='band',
            name='bid_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            code=set_bid_complete,
        ),
        migrations.AlterField(
            model_name='band',
            name='track',
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='bands',
                to='rockonbands.track',
            ),
        ),
        migrations.AlterField(
            model_name='bandmember',
            name='nutrition',
            field=models.CharField(
                choices=[
                    ('unknown', 'Unbekannt'),
                    ('vegan', 'Vegan'),
                    ('vegetarian', 'Vegetarisch'),
                    ('omnivore', 'Omnivore'),
                ],
                default='unknown',
                max_length=12,
            ),
        ),
        migrations.AlterModelOptions(
            name='band',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='bandvote',
            name='event',
            field=models.ForeignKey(
                default='428ce37b-e651-4ad8-b82d-cf75939a6eeb',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='band_votes',
                to='rockonbase.event',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='band',
            name='mean_age_under_27',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='band',
            name='is_coverband',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bandmedia',
            name='media_type',
            field=models.CharField(
                choices=[
                    ('unknown', 'Unbekannt'),
                    ('audio', 'Audio'),
                    ('document', 'Dokument'),
                    ('link', 'Link'),
                    ('logo', 'Logo'),
                    ('press_photo', 'Pressefoto'),
                    ('web', 'Webseite'),
                ],
                default='unknown',
                max_length=32,
            ),
        ),
        migrations.RunPython(
            code=copy_urls_to_bandmedia,
        ),
        migrations.RemoveField(
            model_name='band',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='band',
            name='homepage',
        ),
        migrations.AlterField(
            model_name='band',
            name='contact',
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='bands',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='bandmedia',
            name='file',
            field=models.FileField(
                blank=True,
                default=None,
                max_length=500,
                null=True,
                upload_to=rockon.bands.models.band_media.band_media_path,
            ),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('reason', models.TextField(blank=True, default=None, null=True)),
                (
                    'mood',
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    'band',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='comments',
                        to='rockonbands.band',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='comments',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='band',
            name='bid_status',
            field=models.CharField(
                choices=[
                    ('unknown', 'Unbekannt'),
                    ('pending', 'In Bearbeitung'),
                    ('accepted', 'Bewerbung angenommen'),
                    ('declined', 'Bewerbung abgelehnt'),
                    ('lineup', 'Line Up'),
                ],
                default='unknown',
                max_length=32,
            ),
        ),
        migrations.RunPython(
            code=fix_corrupted_bid_status,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='band',
            name='are_students',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='band',
            name='bid_complete',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='band',
            name='bid_status',
            field=models.CharField(
                choices=[
                    ('unknown', 'Unbekannt'),
                    ('pending', 'In Bearbeitung'),
                    ('accepted', 'Bewerbung angenommen'),
                    ('declined', 'Bewerbung abgelehnt'),
                    ('lineup', 'Line Up'),
                    ('replacement', 'Nachrücker'),
                ],
                db_default='unknown',
                default='unknown',
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name='band',
            name='has_management',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='band',
            name='is_coverband',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='band',
            name='mean_age_under_27',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='band',
            name='repeated',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterUniqueTogether(
            name='bandvote',
            unique_together={('band', 'user')},
        ),
        migrations.CreateModel(
            name='BandReaction',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emoji', models.CharField(max_length=8)),
                (
                    'band',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='reactions',
                        to='rockonbands.band',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='band_reactions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='bandmember',
            name='position',
            field=models.CharField(
                choices=[
                    ('unknown', 'Unbekannt'),
                    ('merch', 'Merchandise'),
                    ('band', 'Band'),
                    ('hand', 'Stagehand'),
                    ('technican', 'Techniker'),
                    ('support', 'Support'),
                    ('media', 'Foto/Video'),
                ],
                default='unknown',
                max_length=12,
            ),
        ),
    ]
