# Generated by Django 4.2.7 on 2023-11-29 08:47

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rockonbands", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="band",
            name="name",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
