# Generated by Django 5.0 on 2023-12-15 14:12

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rockonbands', '0005_bandvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandmedia',
            name='encoded_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
