# Generated by Django 5.0.1 on 2024-01-07 15:13

from __future__ import annotations

from django.db import migrations, models

import rockon.bands.models.band_media


class Migration(migrations.Migration):
    dependencies = [
        ('rockonbands', '0006_bandmedia_encoded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandmedia',
            name='encoded_file',
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to=rockon.bands.models.band_media.band_media_path,
            ),
        ),
    ]
