# Generated by Django 5.0.1 on 2024-01-08 07:59

from __future__ import annotations

from django.db import migrations, models


def set_bid_complete(apps, schema_editor):
    Band = apps.get_model("rockonbands", "Band")
    for band in Band.objects.all():
        band.save()


class Migration(migrations.Migration):
    dependencies = [
        ("rockonbands", "0007_alter_bandmedia_encoded_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="band",
            name="bid_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_bid_complete),
    ]
