# Generated by Django 5.0.1 on 2024-01-11 13:18

from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rockonbands", "0008_band_bid_complete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="band",
            name="track",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bands",
                to="rockonbands.track",
            ),
        ),
    ]
