# Generated by Django 5.0.2 on 2024-02-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rockonbands", "0010_alter_bandmember_nutrition"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="band",
            options={"ordering": ["name"]},
        ),
    ]
