# Generated by Django 5.1 on 2024-08-22 09:52

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rockonbands', '0012_bandvote_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='mean_age_under_27',
            field=models.BooleanField(default=False),
        ),
    ]
