# Generated by Django 5.1 on 2024-08-22 10:33

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rockonbands", "0013_band_mean_age_under_27"),
    ]

    operations = [
        migrations.AddField(
            model_name="band",
            name="is_coverband",
            field=models.BooleanField(default=False),
        ),
    ]
