# Generated by Django 5.1.4 on 2024-12-13 17:45

from __future__ import annotations

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rockonbands', '0016_remove_band_facebook_remove_band_homepage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='contact',
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='bands',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
