# Generated by Django 5.1.4 on 2024-12-13 18:07

from __future__ import annotations

from django.db import migrations, models

import rockon.bands.models.band_media


class Migration(migrations.Migration):
    dependencies = [
        ('rockonbands', '0017_alter_band_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandmedia',
            name='file',
            field=models.FileField(
                blank=True,
                default=None,
                max_length=500,
                null=True,
                upload_to=rockon.bands.models.band_media.band_media_path,
            ),
        ),
    ]
