# Generated by Django 6.0.2 on 2026-02-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rockonbands', '0019_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='bid_status',
            field=models.CharField(
                choices=[
                    ('unknown', 'Unbekannt'),
                    ('pending', 'In Bearbeitung'),
                    ('accepted', 'Bewerbung angenommen'),
                    ('declined', 'Bwerbung abgelehnt'),
                    ('lineup', 'Line Up'),
                ],
                default='unknown',
                max_length=32,
            ),
        ),
    ]
