# Generated by Django 6.0.2 on 2026-02-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rockonbands', '0022_fix_corrupted_bid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='are_students',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='band',
            name='bid_complete',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='band',
            name='bid_status',
            field=models.CharField(
                choices=[
                    ('unknown', 'Unbekannt'),
                    ('pending', 'In Bearbeitung'),
                    ('accepted', 'Bewerbung angenommen'),
                    ('declined', 'Bewerbung abgelehnt'),
                    ('lineup', 'Line Up'),
                ],
                db_default='unknown',
                default='unknown',
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name='band',
            name='has_management',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='band',
            name='is_coverband',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='band',
            name='mean_age_under_27',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='band',
            name='repeated',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
