# Generated by Django 6.0.2 on 2026-02-22 10:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            'rockonbands',
            '0023_alter_band_are_students_alter_band_bid_complete_and_more',
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bandvote',
            unique_together={('band', 'user')},
        ),
    ]
