# Generated by Django 6.0.5 on 2026-05-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rockonbands', '0026_alter_band_bid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandmember',
            name='position',
            field=models.CharField(
                choices=[
                    ('unknown', 'Unbekannt'),
                    ('merch', 'Merchandise'),
                    ('band', 'Band'),
                    ('hand', 'Stagehand'),
                    ('technican', 'Techniker'),
                    ('support', 'Support'),
                    ('media', 'Foto/Video'),
                ],
                default='unknown',
                max_length=12,
            ),
        ),
    ]
