# Generated by Django 6.1.1 on 2026-09-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rockonbands', '0001_initial_squashed_0027_alter_bandmember_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='average_age',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='band',
            name='is_flinta',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
