# Generated by Django 6.1.1 on 2026-09-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rockonbands', '0028_band_average_age_band_is_flinta'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandmedia',
            name='encode_error',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bandmedia',
            name='encode_status',
            field=models.CharField(
                choices=[
                    ('pending', 'Ausstehend'),
                    ('done', 'Fertig'),
                    ('failed', 'Fehlgeschlagen'),
                ],
                db_default='pending',
                default='pending',
                max_length=16,
            ),
        ),
    ]
