# Generated by Django 6.1.1 on 2026-09-30 18:18

from __future__ import annotations

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import rockon.library.guid


class Migration(migrations.Migration):
    dependencies = [
        ('rockonbands', '0029_bandmedia_encode_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BandProfile',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'guid',
                    models.CharField(
                        default=rockon.library.guid.guid, max_length=255, unique=True
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='band_profiles',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='band',
            name='profile',
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='bids',
                to='rockonbands.bandprofile',
            ),
        ),
        migrations.AddConstraint(
            model_name='band',
            constraint=models.UniqueConstraint(
                condition=models.Q(('profile__isnull', False)),
                fields=('profile', 'event'),
                name='unique_bid_per_profile_event',
            ),
        ),
    ]
