# Generated by Django 6.0.2 on 2026-02-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rockontools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkshortener',
            name='counter',
            field=models.IntegerField(db_default=0, default=0),
        ),
    ]
