# Generated by Django 5.0.1 on 2024-01-10 08:50

from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rockoncrew", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crewmember",
            name="crew",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crew_members",
                to="rockoncrew.crew",
            ),
        ),
    ]
