# Generated by Django 5.0.1 on 2024-01-24 09:34

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rockoncrew", "0002_alter_crewmember_crew"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crewmember",
            name="nutrition",
            field=models.CharField(
                choices=[
                    ("unknown", "Unbekannt"),
                    ("vegan", "Vegan"),
                    ("vegetarian", "Vegetarisch"),
                    ("omnivore", "Omnivore"),
                ],
                default="unknown",
                max_length=12,
            ),
        ),
    ]
