# Generated by Django 5.0.6 on 2024-06-27 16:58

from __future__ import annotations

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rockoncrew", "0003_alter_crewmember_nutrition"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestListEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("voucher", models.CharField(max_length=96, unique=True)),
                ("send", models.BooleanField(default=False)),
                (
                    "crew_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guestlist_entries",
                        to="rockoncrew.crewmember",
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guestlist_entries",
                        to="rockoncrew.attendance",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
    ]
