# Generated by Django 6.0.2 on 2026-02-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rockoncrew', '0004_guestlistentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewmember',
            name='nutrition',
            field=models.CharField(
                choices=[
                    ('unknown', 'Unbekannt'),
                    ('vegan', 'Vegan'),
                    ('vegetarian', 'Vegetarisch'),
                    ('omnivore', 'Omnivore'),
                ],
                db_default='unknown',
                default='unknown',
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='state',
            field=models.CharField(
                choices=[
                    ('unknown', 'Unbekannt'),
                    ('confirmed', 'Bestätigt'),
                    ('rejected', 'Abgelehnt'),
                    ('arrived', 'Angekommen'),
                ],
                db_default='unknown',
                default='unknown',
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='stays_overnight',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='state',
            field=models.CharField(
                choices=[
                    ('unknown', 'Unbekannt'),
                    ('confirmed', 'Bestätigt'),
                    ('rejected', 'Abgelehnt'),
                ],
                db_default='unknown',
                default='unknown',
                max_length=12,
            ),
        ),
    ]
