# Generated by Django 6.0.2 on 2026-03-15

from __future__ import annotations

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forward(apps, schema_editor):
    CrewMember = apps.get_model('rockoncrew', 'CrewMember')
    EventTeam = apps.get_model('rockoncrew', 'EventTeam')
    Team = apps.get_model('rockoncrew', 'Team')
    TeamMember = apps.get_model('rockoncrew', 'TeamMember')

    event_team_ids: dict[tuple[str, str], str] = {}

    def get_event_team_id(team_id, event_id):
        key = (str(team_id), str(event_id))
        if key in event_team_ids:
            return event_team_ids[key]

        event_team, _ = EventTeam.objects.get_or_create(
            team_id=team_id,
            event_id=event_id,
        )
        event_team_ids[key] = event_team.id
        return event_team.id

    for team_member in TeamMember.objects.select_related('crewmember__crew').iterator():
        event_team_id = get_event_team_id(
            team_member.team_id,
            team_member.crewmember.crew.event_id,
        )
        team_member.event_team_id = event_team_id
        team_member.save(update_fields=['event_team'])

    role_fields = (
        ('lead', 'lead_id'),
        ('vize_lead', 'vize_lead_id'),
    )
    for team in Team.objects.iterator():
        for role_field, role_id_field in role_fields:
            user_id = getattr(team, role_id_field)
            if user_id is None:
                continue

            event_ids = (
                CrewMember.objects.filter(user_id=user_id)
                .values_list('crew__event_id', flat=True)
                .distinct()
            )
            for event_id in event_ids:
                event_team_id = get_event_team_id(team.id, event_id)
                EventTeam.objects.filter(id=event_team_id).update(
                    **{role_field: user_id}
                )


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rockonbase', '0011_normalize_and_merge_duplicate_emails'),
        (
            'rockoncrew',
            '0005_alter_crewmember_nutrition_alter_crewmember_state_and_more',
        ),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTeam',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'event',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='team_links',
                        to='rockonbase.event',
                    ),
                ),
                (
                    'lead',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='event_team_leads',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'team',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='event_links',
                        to='rockoncrew.team',
                    ),
                ),
                (
                    'vize_lead',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='event_team_vize_leads',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ('event__start', 'team__name'),
                'constraints': [
                    models.UniqueConstraint(
                        fields=('event', 'team'),
                        name='crew_event_team_unique_assignment',
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name='team',
            name='events',
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name='teams',
                through='rockoncrew.EventTeam',
                to='rockonbase.event',
            ),
        ),
        migrations.AddField(
            model_name='teammember',
            name='event_team',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='members',
                to='rockoncrew.eventteam',
            ),
        ),
        migrations.RunPython(forward, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='teammember',
            name='team',
        ),
        migrations.AlterField(
            model_name='teammember',
            name='event_team',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='members',
                to='rockoncrew.eventteam',
            ),
        ),
        migrations.RemoveField(
            model_name='team',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='team',
            name='vize_lead',
        ),
    ]
