# Generated by Django 6.0.5 on 2026-06-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rockoncrew', '0007_crewmember_arrived_boolean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewmember',
            name='state',
            field=models.CharField(
                choices=[
                    ('unknown', 'Unbekannt'),
                    ('confirmed', 'Bestätigt'),
                    ('rejected', 'Abgelehnt'),
                    ('declined', 'Abgesagt'),
                ],
                db_default='unknown',
                default='unknown',
                max_length=12,
            ),
        ),
    ]
