name: Build and publish docker image

permissions:
  contents: read
  packages: write

on:
  # publish on releases, e.g. v2.1.13 (image tagged as "2.1.13" - "v" prefix is removed)
  release:
    types: [ published ]

  # publish on pushes to the main branch (image tagged as "latest")
  push:
    branches:
      # - dev
      - main

jobs:
  docker_build:
    runs-on: "ubuntu-24.04"

    steps:
      - uses: actions/checkout@v5

      # https://github.com/marketplace/actions/push-to-ghcr
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@v16
        with:
          image_name: ${{ github.repository }}
          image_tag: ${{ github.ref_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: docker/Dockerfile

      - name: Notify webhook
        run: |
          curl -X POST ${{ secrets.DEPLOY_PROD_WEBHOOK }}
